In [12]:
import openpyxl
import numpy as np
import pandas as pd
from openpyxl.utils.dataframe import dataframe_to_row

ImportError: cannot import name 'dataframe_to_row' from 'openpyxl.utils.dataframe' (C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\utils\dataframe.py)

In [9]:
df = pd.read_excel('TCR.xlsx', sheet_name='PA_final_table')
df

,TRBV,TRBJ,CDR3β,TRAV,TRAJ,CDR3α,M1LPADN,M1LPATrm,M1SPACM,M1SPAEM,...,M5NoPATrm,M6LPADN,M6LPATrm,M6SPACM,M6SPAEM,M7LPADN,M7LPATrm,M7SPACM,M7SPAEM,Grand Total
0,TRBV17,TRBJ2-5,CASSSNGVDTQYF,ND,ND,ND,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
1,TRBV17,TRBJ2-7,CASSRETGNSYEQYF,ND,ND,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,10
2,TRBV29,TRBJ2-7,CASSLGGYEQYF,TRAV6-4,TRAJ34,CALVPSNTNKVVF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,4.0,8
3,TRBV29,TRBJ2-5,CASSSSDTQYF,TRAV6-6,TRAJ37,CALG##TGNTGKLIF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
4,TRBV29,TRBJ2-3,CASSFGGALYF,TRAV6-6,TRAJ53,CALGGGSNYKLTF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,TRBV12-1,TRBJ2-7,CASSLGLGGNYAEQFF,TRAV9-4,TRAJ21,CAVSAVYGNEKITF,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
492,TRBV17,TRBJ2-5,CASSSNGVDTQYF,TRAV9-4,TRAJ32,ND,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
493,TRBV19,TRBJ1-1,CASSTGANTEVFF,TRAV9-4,TRAJ33,CVLSSXDSNYQLIW,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
494,TRBV12-1,TRBJ2-5,XXXXSXXXXXXXG#,TRAV9-4,TRAJ42,CVXXRGSXXKXXX,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
495,NaN,NaN,NaN,Grand,Total,NaN,24.0,23.0,25.0,24.0,...,37.0,25.0,24.0,23.0,23.0,23.0,23.0,23.0,24.0,637

In [11]:
df = df.sort_values(['TRBJ', 'CDR3β', 'Grand Total'])
df

,TRBV,TRBJ,CDR3β,TRAV,TRAJ,CDR3α,M1LPADN,M1LPATrm,M1SPACM,M1SPAEM,...,M5NoPATrm,M6LPADN,M6LPATrm,M6SPACM,M6SPAEM,M7LPADN,M7LPATrm,M7SPACM,M7SPAEM,Grand Total
107,TRBV2,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
140,ND,ND,ND,TRAV10,TRAJ33,CAASIS#DSNYQLIW,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
157,ND,ND,ND,TRAV12-2,TRAJ22,CALSSGSWQLIF,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
161,ND,ND,ND,TRAV12-2,TRAJ3,CALSYTNAYKVIF,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
185,TRBV3,ND,ND,TRAV12-3,TRAJ22,CALSESSGSWQLIF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,TRBV13-2,TRBJ2-7,XXSGGLPSYEQYF,TRAV12-2,TRAJ53,CALSGSGGGNYKXTF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
348,TRBV29,TRBJ2-7,XXSSLGGYEQYF,TRAV6-4,TRAJ34,CALVPSNTNKVVF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
468,TRBV14,TRBJ2-7,XXXSPYEQYF,TRAV7-4,TRAJ6,CAASXGGNYKXTF,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
284,TRBV17,TRBJ2-7,XXXXXERGXXXEXXX,TRAV2,TRAJ9,CIVTDK#NMGYKLTF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1
495,NaN,NaN,NaN,Grand,Total,NaN,24.0,23.0,25.0,24.0,...,37.0,25.0,24.0,23.0,23.0,23.0,23.0,23.0,24.0,637